name: md2zhihu
on: [push]
permissions:
  contents: write
jobs:
  md2zhihu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: tongyx361/zhihu-md-pub@main
        env:
          GITHUB_USERNAME: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          pattern: >
            _posts/*.md
          asset_repo: https://${{ secrets.GITEE_AUTH }}@gitee.com/tongyx361/assets.git
